version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: marisa_app
    volumes:
      - ~/projects/marisa_recipes:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: marisa_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: tobi312/rpi-mariadb:10.6-alpine
    container_name: marisa_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marisa
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  adminer:
      image: adminer
      container_name: marisa_adminer
      ports:
        - "8081:8080"
      depends_on:
        - db
volumes:
  db_data: